

# specify the node base image with your desired version node:<version>

FROM node:boron

# replace this with your application's default port

EXPOSE 3001

RUN git clone https://github.com/JKU-ICG/fuzzy-spreadsheet.git

WORKDIR /fuzzy-spreadsheet

RUN npm install
RUN npm install -g nodemon

CMD ["run"]

